version: '3.9'

volumes:
  backend_db_data:
  backend_static:

x-base: &base
  restart: unless-stopped
  env_file:
    - .env

x-mount-files: &x-mount-files
  volumes:
    - ./media:${APP_DIR}/../media
    - backend_static:${APP_DIR}/../static


x-backend-base: &backend-base
  <<:
    - *base
    - *x-mount-files
  build:
    dockerfile: ./docker/Dockerfile
    context: ./movies_admin
    args:
      APP_DIR: "${APP_DIR}"
  depends_on:
    - backend_db


services:

  nginx:
    <<:
      - *base
      - *x-mount-files
    image: "nginx:1.25.2-alpine3.18"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/vhosts:/etc/nginx/conf.d:ro
      - ./media:/var/html/media/
      - backend_static:/var/html/static/
    ports:
      - "80:80"
  
  backend:
    <<:
      - *backend-base
    environment:
      START_MODE: BACKEND
  
  backend_db:
    <<:
      - *base
    image: "postgres:15.4-alpine3.18"
    restart: always
    volumes:
      - backend_db_data:/var/lib/postgresql/data
      - ./postgres/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
