# Generated by Django 4.2.3 on 2023-07-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_person_full_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genrefilmwork",
            options={
                "verbose_name": "genre_film_work",
                "verbose_name_plural": "genre_film_works",
            },
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("actor", "actor"),
                    ("director", "director"),
                    ("writer", "writer"),
                ],
                max_length=255,
                verbose_name="role",
            ),
        ),
    ]
