# Generated by Django 4.2.3 on 2023-08-31 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_genrefilmwork_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filmwork",
            name="certificate",
        ),
        migrations.RemoveField(
            model_name="person",
            name="gender",
        ),
    ]
